# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        /:title/

# Setup
title:            situationi.st
tagline:          :rob safar
url:              http://situationi.st
paginate:         1
baseurl:          /
author:
  name:           Rob Safar
  url:            https://twitter.com/robsafar
  email:          whereof@thereof.co.uk

# Custom vars
version:          1.0.0
repository:       https://github.com/whereof-thereof/whereof-thereof.github.io

pages_list:
  About:          '/about'
  Projects:       '/projects'
  Archive:        '/archive'

gems:
  - jekyll-sitemap
