# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Whereof, Thereof
tagline:          – ∀x (∃x) –
url:              http://whereof.thereof.co.uk
paginate:         2
baseurl:          /
author:
  name:           Rob Safar
  url:            https://twitter.com/robsafar
  email:          whereof@thereof.co.uk

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/whereof-thereof/whereof-thereof.github.io

pages_list:       
  About:          '/about'
  Projects:       '/projects'
  Archive:        '/archive'
  RSS:            '/atom.xml'

gems:
  - jekyll-sitemap
