# Site settings
title: "whereof|t͍ͩ̈̆̌̿͊̕͜hereö̡̪̲̲̻̗͖̯͕̌ͦ͞f"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  whereof|t͍ͩ̈̆̌̿͊̕͜hereö̡̪̲̲̻̗͖̯͕̌ͦ͞f
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://whereof.thereof.co.uk" # the base hostname & protocol for your site
twitter_username: robsafar
github_username:  whereof-thereof

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap
