# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        /:title/

# Setup
title:            Whereof, Thereof.
tagline:          ಠ_ರೃ
url:              http://robsafar.co.uk
paginate:         1
baseurl:          /
author:
  name:           Rob Safar
  url:            https://twitter.com/robsafar
  email:          whereof@thereof.co.uk

# Custom vars
version:          1.0.0
repository:       https://github.com/whereof-thereof/whereof-thereof.github.io

pages_list:       
  About:          '/about'
  Projects:       '/projects'
  Archive:        '/archive'
  RSS:            '/atom.xml'

gems:
  - jekyll-sitemap
