# Site settings
title: "Whereof, Thereof."
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  I'm Rob Safar and whereof.thereof is where I keep some of my things. I'm based in London, UK and do Internet things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://whereof.thereof.co.uk" # the base hostname & protocol for your site
twitter_username: robsafar
github_username:  whereof-thereof

# Build settings
markdown: kramdown
gems:
  - jekyll-sitemap